name: siged
description: "Your new database center for roads!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ^3.7.2

flutter_localizations:
  sdk: flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # FIREBASE
  firebase_core: ^4.0.0 #3.13.0 #1.17.1 #1.10.0 #^0.4.5
  firebase_storage: ^13.0.0 #12.4.5 #10.2.17 #10.1.0 #8.0.0 #^3.1.6 #Armazenamento de arquivos no firebase
  firebase_auth: ^6.0.0 #5.5.2 #3.3.19 #3.3.3 #1.0.0 #^0.16.1 #Autenticação do usuário via firebase
  cloud_firestore: ^6.0.0 #5.6.8 #5.6.6 #3.1.17 #3.1.0 #1.0.0 #^0.13.7 #Armazenamento de de dados no firebase

  # LOCAL
  shared_preferences: ^2.5.3

  # CONECTORES
  bloc_pattern: ^3.0.1 #3.0.0 #2.5.1 #^1.5.2 #Cria blocos para fazer o screens.common.login do usuario com seguranca
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0 #0.26.0 #^0.25.0 #Streams e futures
  scoped_model: ^2.0.0 #1.1.0 #Permite que eu acesse os dados do usuario em qualquer pagina
  intl: ^0.20.2 #0.19.0
  provider: ^6.1.5 #6.1.1

  # COORDENADAS
  geolocator: ^14.0.2 #13.0.4 #8.0.0 #^7.7.1 #7.0.0 #6.2.1 #Recupera os ads no mapa
  latlong2: ^0.9.1 #0.9.0 # PEGA AS COORDENADAS
  geocoding: ^4.0.0 #2.2.0 #BUSCA ENDEREÇOS A PARTIR DE COORDENADAS

  # MAPAS
  flutter_map: ^8.2.1 #6.2.1
  #flutter_map_marker_cluster: ^1.1.1
  flutter_map_marker_cluster_plus: ^1.4.2

  # VETORES
  #vector_map_tiles: ^7.3.0
  #vector_tile_renderer: ^5.2.1

  # GRÁFICOS
  fl_chart: ^1.0.0 #0.63.0
  percent_indicator: ^4.2.3
  #lucide_icons: ^0.255.0

  # ACESSO AO DISPOSITIVO
  file_picker: ^10.2.0
  exif: ^3.3.0       # PEGAR INFO DAS FOTOS Mobile/Desktop
  image: ^4.0.2

  flutter_image_compress: ^2.4.0
  #url_launcher: ^6.2.5
  #http: ^1.2.1
  #open_file: ^3.3.2
  #open_filex: ^4.4.0
  #path_provider: ^2.1.2

  # IMAGENS
  image_picker: ^1.2.0 #1.1.2 #0.8.4+4 #0.7.0 #^0.6.7+22 #Recupera imagem da camera e galeria
  image_cropper: ^9.1.0


  # ANIMAÇÕES
  #rive: ^0.13.20
  shimmer: ^3.0.0

  #vector_math: ^2.1.4
  #web: ^1.1.0
  #permission_handler: ^11.3.1

  # MÁSCARAS
  flutter_multi_formatter: ^2.9.0  # ou a versão mais recente
  cpf_cnpj_validator: ^2.0.0 #^1.0.5 #Validador de CPF e CNPJ
  brasil_fields: ^1.18.0 #1.15.0 #1.0.0 #0.6.1 #Adaptar valores para o formato de moeda brasileira
  mask_text_input_formatter: ^2.4.0
  diacritic: ^0.1.3 #REMOVER ACENTOS

  #
  datetime_picker_formfield: 2.0.1 #1.0.0 #Formulário de input tipo date

  #CONECTORES
  excel: ^4.0.6 #2.0.6
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # (opcional, se usar ícones adaptativos)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 #5.0.0

flutter:
  fonts:
    - family: Halter
      fonts:
        - asset: assets/fonts/halter.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/geojson/roads/state_roads.geojson
    - assets/geojson/limits/limites_regionais_der_al.geojson
    - assets/geojson/limits/limites_cidades_al.geojson
    - assets/geojson/roads/state_bridges.geojson
    - assets/logos/deral/logo-deral.png
    - assets/images/default_avatar.png
    - assets/logos/siged/siged.png
    - assets/icons/pdf-file-format.png
    - assets/icons/wait-to-up-file.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
