name: siged
description: "Your new database center for roads!"
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=3.7.2 <4.0.0"   # ou o range que você estiver usando

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   # ⬅️ AQUI dentro de dependencies
    sdk: flutter

  cupertino_icons: ^1.0.8

  # FIREBASE
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # LOCAL
  shared_preferences: ^2.5.3

  # CONECTORES
  bloc_pattern: ^3.0.1
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  scoped_model: ^2.0.0
  intl: ^0.20.2
  provider: ^6.1.5

  # COORDENADAS
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0

  # MAPAS
  flutter_map: ^8.2.1
  flutter_map_marker_cluster_plus: ^1.4.2

  # GRÁFICOS
  fl_chart: ^1.0.0
  percent_indicator: ^4.2.3

  # ACESSO AO DISPOSITIVO
  file_picker: ^10.2.0
  exif: ^3.3.0
  image: ^4.0.2
  flutter_image_compress: ^2.4.0
  syncfusion_flutter_pdfviewer: ^28.2.7
  pdfx: ^2.6.0

  # IMAGENS
  image_picker: ^1.2.0
  image_cropper: ^9.1.0

  # ANIMAÇÕES
  shimmer: ^3.0.0

  # MÁSCARAS
  flutter_multi_formatter: ^2.9.0
  cpf_cnpj_validator: ^2.0.0
  brasil_fields: ^1.18.0
  mask_text_input_formatter: ^2.4.0
  diacritic: ^0.1.3

  # DATE INPUT
  datetime_picker_formfield: 2.0.1

  # CONECTORES
  excel: ^4.0.6
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Halter
      fonts:
        - asset: assets/fonts/halter.ttf

  assets:
    - assets/geojson/roads/state_roads.geojson
    - assets/geojson/limits/limites_regionais_der_al.geojson
    - assets/geojson/limits/limites_cidades_al.geojson
    - assets/geojson/roads/state_bridges.geojson
    - assets/logos/deral/logo-deral.png
    - assets/images/default_avatar.png
    - assets/logos/siged/siged.png
    - assets/icons/pdf-file-format.png
    - assets/icons/wait-to-up-file.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
