name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'      # ajuste para a versão que você usa
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      # Se ainda não tiver testes configurados, pode comentar este bloco
      - name: Run tests
        run: flutter test

      # Opcional: build web (se você quiser garantir que o build funciona)
      # - name: Build Flutter web
      #   run: flutter build web --release
